security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email # Le champ utilis√© pour l'identification
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            # üöÄ AJOUT DE LA CONFIGURATION DE CONNEXION (FORM_LOGIN) üöÄ
            form_login:
                login_path: app_login       # Route pour afficher le formulaire de connexion (GET)
                check_path: app_login       # Route qui traite la soumission du formulaire (POST)
                enable_csrf: true
                # üõ†Ô∏è CORRECTION : Remplacer 'target' par 'default_target_path'
                default_target_path: app_home # Redirection apr√®s succ√®s. Assurez-vous que 'app_home' existe.
                username_parameter: email   # Nom du champ d'identification dans le formulaire
                password_parameter: password # Nom du champ du mot de passe dans le formulaire
            
            # üöÄ AJOUT DE LA CONFIGURATION DE D√âCONNEXION üöÄ
            logout:
                path: app_logout
                target: app_home # Redirection apr√®s d√©connexion

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    # üöÄ AJOUT DE LA GESTION DES ACC√àS üöÄ
    access_control:
         # Permettre √† tout le monde d'acc√©der aux pages de connexion et d'inscription
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }
        # Exemple: Interdire l'acc√®s √† /admin aux non-admins
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # Exiger une connexion pour toutes les autres pages (si vous d√©commentez ceci)
        # - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        
when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
